### ISSUE TITLE
Force BBO to 6 digits

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AppealsCivilDocketingStatement#14]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Attorney BBO`
logic | This should only allow the user to progress if they enter a six digit number.
Other information | 
Variable being sought | `attorneys[0].bbo`
Package version | `0.0.1`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Tester contact info | Paul Tuttle (Appeals Court)

**Comment by BryceStevenWilley** [comment]
This is related to https://github.com/SuffolkLITLab/docassemble-AssemblyLine/issues/18, which I'll handle soon :tm:.
