### ISSUE TITLE
ID appeals basic questions intro screen: 
User feedback: something
(`appeals_basic_questions_intro_screen`)

### ISSUE THREAD

**Issue by suffolk-auto-issues** [SuffolkLITLab/docassemble-AppealsCivilDocketingStatement#22]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `appeals basic questions intro screen`
Details | nthnth
Variable being sought | `appeals_basic_questions_intro_screen`
Package version | `0.0.6`
Filename | `docassemble.AppealsCivilDocketingStatement:data/questions/civil_docketing_statement_standalone.yml`

**Comment by BryceStevenWilley** [comment]
Was a testing issue from test
